mixed fixed up hopefully

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,10 +27,12 @@ jobs:
       - uses: btungut/devops/.github/actions/common@master
         id: common
 
+        
       - uses: btungut/devops/.github/actions/git-checkout@master
         with:
           gitToken: ${{ secrets.GITHUB_TOKEN }}
       
+
       - name: dotnet_restore_and_build
         id: dotnet_restore_and_build
         shell: bash
@@ -40,6 +42,8 @@ jobs:
           dotnet build -c Release
         working-directory: app
 
+
+        # run tests and publish cobertura report
       - name: dotnet_test
         id: dotnet_test
         shell: bash
@@ -47,17 +51,8 @@ jobs:
           set -euo pipefail
           rm -rf ./coverage*
           dotnet test --collect:"XPlat Code Coverage" --results-directory ./coverage -c Release --no-build --no-restore --verbosity normal
-          
-          # find *.xml file abs path which under ./coverage directory, if not exist echo and exit
-          coverage_files=$(find ./coverage -name '*.xml')
-          if [ $(echo "$coverage_files" | wc -l) -ne 1 ]; then
-            echo "Coverage file not found or found more than one: $coverage_files"
-            exit 1
-          fi
-          
-          # add env var for coverage file path
-          echo "##[set-output name=coverage_file_path;]$coverage_files"
         working-directory: app/tests
+
 
       - name: copy_coverage_files
         shell: bash
@@ -73,16 +68,46 @@ jobs:
 
           cp $coverage_files ${{ runner.temp }}/result.xml
 
+
       - uses: danielpalme/ReportGenerator-GitHub-Action@5.4.3
         with:
           reports: ${{ runner.temp }}/result.xml
           reporttypes: "Html;MarkdownSummaryGithub;Cobertura"
           toolpath: 'reportgeneratortool'
           targetdir: ${{ runner.temp }}/coveragereport
+          tag: ${{ runner.name }}
+
+
+      - name: check_it
+        shell: bash
+        run: |
+          set -euo pipefail
+          ls -al
+        working-directory: ${{ runner.temp }}/coveragereport
+          
 
       - name: Upload coverage report artifact
         uses: actions/upload-artifact@v4
         with:
           name: CoverageReport # Artifact name        
-          path: ${{ runner.temp }}/coveragereport # Directory containing files to upload
-        
+          path: ${{ runner.temp }}/coveragereport # Directory containing files to upload         
+
+
+      - name: Publish coverage in build summary
+        run: |
+          set -euo pipefail
+          ls -al
+          # find md file, if not exist or exist more than one fail, else get the path
+          md_files=$(find ${{ runner.temp }}/coveragereport -name '*.md')
+          if [ $(echo "$md_files" | wc -l) -ne 1 ]; then
+            echo "Markdown file not found or found more than one: $md_files"
+            exit 1
+          fi
+          
+          echo "### REPORT : $md_files"
+          cat $md_files
+          echo "### REPORT END"
+
+          cat $md_files >> $GITHUB_STEP_SUMMARY
+        shell: bash
+        working-directory: ${{ runner.temp }}/coveragereport
