Update CI workflow to copy coverage report to temporary directory and upload as artifact

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -62,18 +62,35 @@ jobs:
             exit 1
           fi
 
-          cp $coverage_files result.xml
+          cp $coverage_files ${{ runner.temp }}/result.xml
 
-
-      - name: irongut_coverage
-        uses: irongut/CodeCoverageSummary@v1.3.0
+      - uses: danielpalme/ReportGenerator-GitHub-Action@5.4.3
         with:
-          filename: result.xml
-          badge: true
-          fail_below_min: true
-          format: markdown
-          hide_branch_rate: false
-          hide_complexity: false
-          indicators: true
-          output: both
-          thresholds: '50 75'
+          reports: result.xml
+          targetdir: ${{ runner.temp }}
+          reporttypes: "HtmlInline;Cobertura"
+          toolpath: 'reportgeneratortool'
+
+      - name: Upload coverage report artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: CoverageReport # Artifact name        
+          path: coveragereport # Directory containing files to upload
+
+      - shell: bash
+        run: |
+          set -euo pipefail
+          tree
+
+      # - name: irongut_coverage
+      #   uses: irongut/CodeCoverageSummary@v1.3.0
+      #   with:
+      #     filename: result.xml
+      #     badge: true
+      #     fail_below_min: true
+      #     format: markdown
+      #     hide_branch_rate: false
+      #     hide_complexity: false
+      #     indicators: true
+      #     output: both
+      #     thresholds: '50 75'
